theme: jekyll-theme-minimal
title: Byun, Han Joon
description: Han Joon Byun is a researcher at Seoul National University working on tabular data, time series, finance, machine learning, and optimization.
url: https://byunhanjoon.github.io
